cubes:
- name: payer_360_gpo_benefit_type_config
  sql_table: '"oasis-dev-cube-poc".payer_360_gpo_benefit_type_config'
  data_source: default
  public: false
  refresh_key:
    every: 5 minute
  dimensions:
  - name: benefit_type
    sql: benefit_type
    type: string
    work: name
    meta:
      owner: Arput
      use_cases: tells benefit
      kpi: true
    title: Benefit Type
    description: This field tells the benefit type by Manish before commit
  - name: gpo_name
    sql: gpo_name
    type: string
    meta:
      owner: Manish
      domain: config type
      use_cases: not working
      kpi: false
    title: Name of Gpo
    description: This field tells the  gpo name by Manish
  measures:
  - name: count
    type: count
    meta:
      owner: Harish
      kpi: false
    title: Total Count
    description: This field tells the count of the rows
